# Generated by Django 5.2.3 on 2025-07-02 15:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('formation', 'Formation'), ('conference', 'Conférence'), ('atelier', 'Atelier')], max_length=50)),
                ('location', models.CharField(choices=[('digital', 'Digital'), ('fablab', 'Fab Lab')], max_length=50)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
