# Generated by Django 5.2.3 on 2025-07-21 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('formation', 'Formation'), ('conference', 'Conférence'), ('talk', 'Talk'), ('open_lab', 'Open Lab'), ('fab_cafe', 'Fab Café'), ('master_class', 'Master Class'), ('atelier', 'Atelier'), ('super_codeurs', 'Super Codeurs'), ('maker_junior', 'Maker Junior')], max_length=50)),
                ('location', models.CharField(choices=[('digital', 'Digital'), ('fablab', 'Fab Lab'), ('fab', 'Fab'), ('odc_clubs', 'ODC Clubs')], max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
