"""
Django settings for OrangeDigitalCenter project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os.path
from pathlib import Path

from django.conf.global_settings import AUTH_USER_MODEL, CSRF_TRUSTED_ORIGINS, LOGIN_URL, LOGIN_REDIRECT_URL, \
    LOGOUT_REDIRECT_URL

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-liwwc^@%76!h4)+)0d!o)+(i5(5n-ullw$hq%bf6py0of$(8(0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'frontoffice',
    'events',
    'applications',
    'reporting',
    'attendance',
    'backoffice',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # Doit être présent
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Configuration CSRF
CSRF_COOKIE_SECURE = False  # True en production (HTTPS)
CSRF_COOKIE_HTTPONLY = False  # Doit être False pour que JavaScript puisse le lire
CSRF_USE_SESSIONS = False
CSRF_COOKIE_SAMESITE = 'Lax'  # 'Strict' peut causer des problèmes lors de la redirection

# Configuration des sessions
SESSION_COOKIE_SECURE = False  # True en production
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

CSRF_TRUSTED_ORIGINS = ['http://192.168.0.1', 'http://Orangedigitalcenter.com']

ROOT_URLCONF = 'OrangeDigitalCenter.urls'

ALLOWED_HOSTS = ['localhost', '127.0.0.1']

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'OrangeDigitalCenter.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
LOGIN_URL = 'login' #nom de la vue de login

LOGIN_REDIRECT_URL = 'home' # vue "home" par defaut pour frontoffice non-admin

LOGOUT_REDIRECT_URL = 'home'
AUTH_USER_MODEL = 'frontoffice.CustomUser'
LOGOUT_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/frontoffice/login/'
# URL de la page de connexion
LOGIN_URL = '/backoffice/login/'
# Redirection après connexion
LOGIN_REDIRECT_URL = '/backoffice/dashboard/'
# Redirection après déconnexion
LOGOUT_REDIRECT_URL = '/backoffice/login/'

# Authentification backend
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Modèle utilisateur personnalisé
AUTH_USER_MODEL = 'frontoffice.CustomUser'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Fichiers média
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS =[
    BASE_DIR/ "static"
]
STATIC_ROOT = BASE_DIR/ "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
